name: 定时修改步数
on:
  schedule:
    - cron: '0 8,12,15,17,21 * * *'
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17.7
        uses: actions/setup-go@v1
        with:
          go-version: 1.17.7
        id: go

      - name: Check out source code
        uses: actions/checkout@v1

      - name: Build
        run: go build -o custom_step ./cmd

      - name: run
        run: |
          user='${{ secrets.USER }}'
          passwd='${{ secrets.PWD }}'
          ./custom_step -user 13667279129 -password xxxx